# Generated by Django 5.0.1 on 2024-02-07 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.maincategory'),
        ),
    ]
