# Generated by Django 5.0.1 on 2024-03-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0004_remove_productimage_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.product'),
        ),
    ]
