# Generated by Django 5.0.1 on 2024-03-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0005_size_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='SellerApp.productimage'),
        ),
    ]
