# Generated by Django 5.0.1 on 2024-04-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0007_alter_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.productimage'),
        ),
    ]
