# Generated by Django 5.0.1 on 2024-04-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerApp', '0008_remove_product_images_remove_productimage_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_id',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='SellerApp.productimage'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerApp.product'),
        ),
    ]
