# Generated by Django 5.0.1 on 2024-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
    ]
