# Generated by Django 5.0.1 on 2024-02-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
