# Generated by Django 5.0.1 on 2024-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_buyproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
