# Generated by Django 5.0.1 on 2024-03-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_wishlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
